---
- name: Install dependencies
  become: yes
  apt: pkg={{item}} state=installed
  with_items:
    - nodejs
    - npm

- name: Adding node to os_path
  become: yes
  file:
    src: /usr/bin/nodejs
    dest: /usr/bin/node
    state: link
